/*
 * spec/i123/wk1_format.h -- the Lotus 1-2-3 Release 2.2 .WK1 record set the
 * Initech 123 codec reads and writes (LOCKED SPEC-DATA, Rule 8).
 *
 * bead: initech-9u8w (I123 P1: grid + labels + numbers + .WK1 round-trip).
 *       Plan: docs/plans/INITECH-123-plan.md Sec 4 (the record table there is
 *       a HYPOTHESIS; every value below is re-derived from the real goldens).
 *
 * Ref (Law 1; corpus = ../lotus123-decomp, the real 1-2-3 R2.2 under DOSBox-X):
 *   specs/file-formats/wk1-format.md  Sec 1 (framing), Sec 2 (opcode/length
 *     table over 44 goldens), Sec 3 (header records), Sec 4 (cell records),
 *     Sec 4.9 (INTEGER vs NUMBER), Sec 9 (what a conforming writer emits);
 *   goldens/minted/MINT01.WK1 (a FRESH sheet written by 123.EXE: the record
 *     order and every default body of DEFAULT_TEMPLATE below, offsets cited
 *     per record), MINT02 (COLW1, WINDOW1 ncols 7), MINT04 (CALCMODE 0x00,
 *     CALCORDER 0x01, CALCCOUNT 7, PROTEC 0xFF), MINT05 (the INTEGER/NUMBER
 *     boundary), and the 38 shipped sample sheets.
 *
 * INDEPENDENCE BARRIER (ADR-0008 DEC-05, as the corpus CLAUDE.md applies it):
 * nothing here is copied from tools/wk1_ref.py -- the opcodes and lengths are
 * the bytes of the goldens, and the oracle that grades the C codec
 * (test-i123-wk1-roundtrip) reads the same files through wk1_ref.py, which
 * shares no constant with this header.
 *
 * Facts this lane VERIFIED over all 44 goldens (2026-10-04, scratch survey,
 * re-runnable from the oracle): every model-owned record below occurs exactly
 * once; the cell records form ONE contiguous run in row-major order directly
 * before EOF; COLW1 records directly follow WINDOW1, ascending by column; the
 * WINDOW1 "columns visible" field equals the number of whole columns, from
 * the WINDOW1 left column, whose widths fit I123_SCREEN_COLS_CHARS (44/44).
 *
 * Freestanding: <stdint.h> only. ASCII-clean (Rule 12).
 */
#ifndef INITECH_SPEC_I123_WK1_FORMAT_H
#define INITECH_SPEC_I123_WK1_FORMAT_H

#include <stdint.h>

/* --- 1. Framing: u16 opcode, u16 body length, body (wk1-format.md Sec 1;
 *        MINT01 @0x0000 `00 00 02 00 06 04`). ------------------------------ */
#define WK1_REC_HDR          4u
#define WK1_BOF_VERSION      0x0406u   /* all 44 goldens                       */

/* --- 2. Opcodes the model OWNS (decoded, regenerated by the writer). ------ */
#define WK1_OP_BOF           0x0000u   /* len 2                                */
#define WK1_OP_EOF           0x0001u   /* len 0                                */
#define WK1_OP_CALCMODE      0x0002u   /* len 1: 0xFF auto, 0x00 manual (MINT04 @0x2d) */
#define WK1_OP_CALCORDER     0x0003u   /* len 1: 0x00 natural, 0x01 columnwise (MINT04 @0x32) */
#define WK1_OP_SPLIT         0x0004u   /* len 1                                */
#define WK1_OP_SYNC          0x0005u   /* len 1                                */
#define WK1_OP_RANGE         0x0006u   /* len 8: i16 c0,r0,c1,r1               */
#define WK1_OP_WINDOW1       0x0007u   /* len 32                               */
#define WK1_OP_COLW1         0x0008u   /* len 3: u16 col, u8 width (MINT02 @0x5f) */
#define WK1_OP_PROTEC        0x0024u   /* len 1: 0x00 off, 0xFF on (MINT04 @0x193) */
#define WK1_OP_LABELFMT      0x0029u   /* len 1: default label prefix (0x27)   */
#define WK1_OP_CALCCOUNT     0x002Fu   /* len 1: iterations (MINT04 @0x28 = 7) */
#define WK1_OP_UNFORMATTED   0x0030u   /* len 1                                */
#define WK1_OP_HIDVEC1       0x0096u   /* len 6n: (u16 col, u16 first, u16 last)* */

/* Cell records: body = u8 format, u16 col, u16 row, then the payload
 * (wk1-format.md Sec 4; MINT01 @0x58c INTEGER `ff 01 00 00 00 7b 00`). */
#define WK1_OP_BLANK         0x000Cu   /* len 5                                */
#define WK1_OP_INTEGER       0x000Du   /* len 7: + i16                         */
#define WK1_OP_NUMBER        0x000Eu   /* len 13: + IEEE binary64 LE           */
#define WK1_OP_LABEL         0x000Fu   /* len 5 + prefix + text + NUL          */
#define WK1_OP_FORMULA       0x0010u   /* len 15 + codeLen: + f64 cache, u16 codeLen, RPN */
#define WK1_OP_STRING        0x0033u   /* len 5 + text + NUL: a string formula's result,
                                        * directly after its FORMULA (110/110) */

#define WK1_CELL_PREFIX      5u
#define WK1_LEN_ONE          1u
#define WK1_LEN_BOF          2u
#define WK1_LEN_RANGE        8u
#define WK1_LEN_WINDOW1      32u
#define WK1_LEN_COLW1        3u
#define WK1_HIDVEC_TRIPLE    6u
#define WK1_LEN_BLANK        5u
#define WK1_LEN_INTEGER      7u
#define WK1_LEN_NUMBER       13u
#define WK1_FORMULA_FIXED    15u      /* prefix 5 + f64 8 + codeLen 2          */

/* --- 3. WINDOW1 field offsets (wk1-format.md Sec 3.4; MINT01 @0x47 body
 *        `03 00 01 00 71 00 09 00 08 00 14 00 00 00 ...`). ----------------- */
#define WK1_W1_CUR_COL       0u
#define WK1_W1_CUR_ROW       2u
#define WK1_W1_FMT           4u        /* global default cell format (0x71 General) */
#define WK1_W1_WIDTH         6u        /* global column width (9)              */
#define WK1_W1_NCOLS         8u        /* columns visible -- DERIVED, see below */
#define WK1_W1_NROWS         10u       /* 20 in all 44                         */
#define WK1_W1_LEFT          12u       /* leftmost visible column              */
#define WK1_W1_TOP           14u

/* The worksheet area of the 80-column screen is 80 - the 4-character row
 * border = 76 characters, and WINDOW1 ncols counts the whole columns that fit
 * in 72 of them: verified 44/44 (MINT01 widths 9 -> 8; MINT02 col A 12 -> 7;
 * SAMP4X/SAMPBAL/... 7; TUTOR11X 5 ...). */
#define I123_SCREEN_COLS_CHARS  72u

/* The fresh WINDOW1 body 123.EXE writes (MINT01 @0x47, cursor zeroed: the
 * model owns bytes 0..9 and writes the cursor, format, width and ncols). */
#define WK1_W1_DEFAULT_INIT { \
    0x00,0x00, 0x00,0x00, 0x71,0x00, 0x09,0x00, 0x08,0x00, 0x14,0x00, \
    0x00,0x00, 0x00,0x00, 0x00,0x00, 0x00,0x00, 0x00,0x00, 0x00,0x00, \
    0x04,0x00, 0x04,0x00, 0x48,0x00, 0x00,0x00 }

/* --- 4. Fresh-sheet one-byte defaults (MINT01; wk1-format.md Sec 3.2). ---- */
#define WK1_DEF_CALCMODE     0xFFu     /* automatic                            */
#define WK1_DEF_CALCORDER    0x00u     /* natural                              */
#define WK1_DEF_CALCCOUNT    0x01u
#define WK1_DEF_SPLIT        0x00u
#define WK1_DEF_SYNC         0xFFu
#define WK1_DEF_PROTEC       0x00u
#define WK1_DEF_LABELFMT     0x27u     /* ' left-aligned                       */
#define WK1_DEF_UNFORMATTED  0x00u

/* --- 5. Cell format byte (wk1-format.md Sec 4.8). Bit 7 = protect flag (as
 *        the corpus reads it; GAPS F-5 [oracle-resolves]), bits 6..4 type,
 *        bits 3..0 decimals or special code. ------------------------------- */
#define WK1_FMT_PROTECT      0x80u
#define WK1_FMT_TYPE(b)      (((b) >> 4) & 7u)
#define WK1_FMT_LOW(b)       ((b) & 15u)
#define WK1_FT_FIXED         0u        /* MINT02 Fixed3 = 0x83, "1234.500"     */
#define WK1_FT_SCI           1u
#define WK1_FT_CURRENCY      2u        /* MINT02 Currency2 = 0xA2, "$1,234.63" */
#define WK1_FT_PERCENT       3u        /* MINT02 Percent1 = 0xB1, "12.5%"      */
#define WK1_FT_COMMA         4u
#define WK1_FT_SPECIAL       7u
#define WK1_FS_PLUSMINUS     0u
#define WK1_FS_GENERAL       1u        /* 0x71 / 0xF1                          */
#define WK1_FS_D1            2u        /* DD-MMM-YY: MINT02 0xF2, "09-Mar-92"  */
#define WK1_FS_D2            3u        /* DD-MMM                               */
#define WK1_FS_D3            4u        /* MMM-YY                               */
#define WK1_FS_TEXT          5u
#define WK1_FS_HIDDEN        6u
#define WK1_FS_DEFAULT       15u       /* 0x7F / 0xFF: use WINDOW1 byte 4      */
#define WK1_FMT_FRESH_CELL   0xFFu     /* every cell 123.EXE wrote in the minted set */

/* --- 6. Label prefix characters (wk1-format.md Sec 4.4; counts over 44). -- */
#define WK1_PFX_LEFT         0x27u     /* '                                    */
#define WK1_PFX_RIGHT        0x22u     /* "  (MINT02 @0x612 "Right", shot right-aligned) */
#define WK1_PFX_CENTER       0x5Eu     /* ^                                    */
#define WK1_PFX_REPEAT       0x5Cu     /* \                                    */
#define WK1_PFX_NOPRINT      0x7Cu     /* |                                    */

/* --- 7. Typed-literal storage rule (wk1-format.md Sec 4.9, MINT05):
 *        32767 -> INTEGER; 32768, -32768, -32769 -> NUMBER. -32767 was never
 *        minted; the symmetric bound below is [inferred] (GAPS N-2/N-8). ---- */
#define WK1_INT_MAX          32767
#define WK1_INT_MIN          (-32767)

/* --- 8. Sheet geometry (Release 2.2: 256 columns A..IV, 8192 rows). ------- */
#define I123_MAX_COLS        256u
#define I123_MAX_ROWS        8192u

/* --- 9. THE FRESH-SHEET TEMPLATE: every non-cell record 123.EXE writes into
 *        a fresh sheet, in MINT01's order (wk1-format.md Sec 1.1 / Sec 9),
 *        derived byte-for-byte from goldens/minted/MINT01.WK1.
 *
 * Encoding (so 1.3 KB of mostly 00/FF stays reviewable): each record is
 * `op_lo, op_hi, len_lo, len_hi` then, when len > 0, runs of (count, byte)
 * terminated by a 0 count, the counts summing to len. len == 0 marks a
 * MODEL-OWNED placeholder: the writer emits the record from the model there
 * (WINDOW1's placeholder also emits the COLW1 group). BOF and EOF are not in
 * the template (always first / last). The run counts are checked against the
 * lengths by the host oracle. ---------------------------------------------- */
#define WK1_DEFAULT_TEMPLATE_INIT { \
    /* @0x006 RANGE       */ 0x06,0x00, 0x00,0x00, \
    /* @0x012 HIDVEC1     */ 0x96,0x00, 0x00,0x00, \
    /* @0x02e CALCCOUNT   */ 0x2f,0x00, 0x00,0x00, \
    /* @0x033 CALCMODE    */ 0x02,0x00, 0x00,0x00, \
    /* @0x038 CALCORDER   */ 0x03,0x00, 0x00,0x00, \
    /* @0x03d SPLIT       */ 0x04,0x00, 0x00,0x00, \
    /* @0x042 SYNC        */ 0x05,0x00, 0x00,0x00, \
    /* @0x047 WINDOW1     */ 0x07,0x00, 0x00,0x00, \
    /* @0x06b op 0x64 32  */ 0x64,0x00, 0x20,0x00, 32,0x00, 0, \
    /* @0x08f op 0x18 25  */ 0x18,0x00, 0x19,0x00, 1,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, \
                             2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x0ac op 0x19 25  */ 0x19,0x00, 0x19,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 3,0x00, 0, \
    /* @0x0c9 op 0x1a 8   */ 0x1a,0x00, 0x08,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x0d5 UNFORMATTED */ 0x30,0x00, 0x00,0x00, \
    /* @0x0da op 0x1c 8   */ 0x1c,0x00, 0x08,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x0e6 op 0x1b 8   */ 0x1b,0x00, 0x08,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x0f2 op 0x1d 9   */ 0x1d,0x00, 0x09,0x00, 2,0xff, 2,0x00, 2,0xff, 3,0x00, 0, \
    /* @0x0ff op 0x23 9   */ 0x23,0x00, 0x09,0x00, 2,0xff, 2,0x00, 2,0xff, 3,0x00, 0, \
    /* @0x10c op 0x67 25  */ 0x67,0x00, 0x19,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 3,0x00, 0, \
    /* @0x129 op 0x69 40  */ 0x69,0x00, 0x28,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x155 op 0x20 16  */ 0x20,0x00, 0x10,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x169 op 0x66 16  */ 0x66,0x00, 0x10,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x17d PROTEC      */ 0x24,0x00, 0x00,0x00, \
    /* @0x182 FOOTER 242  */ 0x25,0x00, 0xf2,0x00, 242,0x00, 0, \
    /* @0x278 HEADER 242  */ 0x26,0x00, 0xf2,0x00, 242,0x00, 0, \
    /* @0x36e SETUP 40    */ 0x27,0x00, 0x28,0x00, 40,0x00, 0, \
    /* @0x39a MARGINS 10  */ 0x28,0x00, 0x0a,0x00, 1,0x04, 1,0x00, 1,0x4c, 1,0x00, 1,0x42, \
                             1,0x00, 1,0x02, 1,0x00, 1,0x02, 1,0x00, 0, \
    /* @0x3a8 LABELFMT    */ 0x29,0x00, 0x00,0x00, \
    /* @0x3ad TITLES 16   */ 0x2a,0x00, 0x10,0x00, 2,0xff, 2,0x00, 2,0xff, 2,0x00, 2,0xff, \
                             2,0x00, 2,0xff, 2,0x00, 0, \
    /* @0x3c1 NGRAPH 439  */ 0x2d,0x00, 0xb7,0x01, 104,0xff, 1,0x04, 2,0x00, 6,0x03, \
                             255,0x00, 65,0x00, 2,0x71, 1,0x01, 3,0x00, 0 }

#endif /* INITECH_SPEC_I123_WK1_FORMAT_H */
