/*
 * os/flair/finder_ops.h -- the R3.4a Finder FILE OPERATIONS: drag-move and
 * drag-to-Trash staging (THE ARTIFACT).
 *
 * beads: initech-34dh (GUI remediation R3.4, reslice 1/3 of initech-tdnl.11:
 *        the finder_fs_t binding extension, drop-target resolution, the
 *        refusal ladder, Trash staging with the collision suffix, and the
 *        kind=5 trash-origin records).
 *
 * WHAT A USER SEES (and the period references it follows)
 *   1. Press on an icon in a disk window and move past FINDER_DRAG_SLOP: a GRAY
 *      OUTLINE of the icon cell (sprite + name) follows the pointer; the icon
 *      itself stays put. Inside Macintosh: Macintosh Toolbox Essentials p. 4-97
 *      (DragGrayRgn "moves a gray outline of a region on the screen, following
 *      the movements of the cursor, until the mouse button is released") and
 *      Apple patent US5754178A (filed 1993-03-03) on the System 7 Finder: "an
 *      outline image representation of the icon and its file name ... to be
 *      moved on the computer system display".
 *   2. While the pointer is over a VALID DROP TARGET -- a folder icon in any
 *      disk window, the volume icon, or the Trash icon -- that target is drawn
 *      in its HIGHLIGHTED state (darkened body, inverted name) and returns to
 *      normal the moment the pointer leaves it. US5754178A: "When the 'folder'
 *      icon 140 is pointed to by pointer 110, it becomes shown in its
 *      highlighted state"; the darkened look is IM VI p. 2-19..2-20 (see
 *      os/flair/finder_icon.h :: finder_icon_draw_hilite). Window CONTENT is a
 *      target too but is not highlighted (the period Finder had no window-body
 *      destination feedback in 7.x; the icon simply lands where dropped).
 *   3. A drop that is REFUSED (the ladder below) or lands on NO target: the
 *      outline ZOOMS BACK to the icon's original cell and nothing on the volume
 *      changes. US5754178A: "the abort may be indicated by series of 'zooming
 *      rectangles' ... generated by the subroutine ZoomRects()" which "head back
 *      towards the original folder". The animation is a live-pump concern
 *      (os/milton/kmain.c); this module only reports WHY.
 *   Local copies of the quoted passages: docs/research/
 *   finder-drag-feedback-ground-truth.md.
 *
 * THE DROP TARGETS (finder_ops_resolve; window-RELATIVE where it matters)
 *   point in a Finder disk window's CONTENT (FindWindow == inContent):
 *       on a FOLDER icon other than the dragged one  -> FOLDER (into it)
 *       otherwise, the dragged icon's OWN window      -> REPOSITION (R3.3 drag)
 *       otherwise                                     -> WINDOW (into its dir)
 *   point on bare desktop (FindWindow == inDesk):
 *       on the Trash icon   -> TRASH  (stage into \TRASH)
 *       on the volume icon  -> VOLUME (into the root, dir 0)
 *       anywhere else       -> NONE
 *   anything else (title bars, other tenants' windows, menu bars) -> NONE.
 *   A FOLDER or WINDOW target whose directory IS \TRASH stages exactly like
 *   the Trash icon (origin recorded), so the two routes cannot disagree.
 *   The icon hit test runs on the target window's OWN icon model
 *   (finder_desk_hit on that window's view), and an icon moved INTO a window
 *   lands at the drop point measured RELATIVE to that window's content rect
 *   and re-based onto its view, so both stay right if the view's coordinate
 *   origin ever stops being the screen.
 *
 * THE REFUSAL LADDER (finder_ops_drop; checked in THIS order, first wins)
 *   service  the source (or the resulting destination) is the Finder's own
 *            \TRASH or \DESKTOP.DB, by identity (finder_win_is_service;
 *            beads initech-tdnl.73/.75)            FINDER_WIN_ERR_SERVICE
 *   samedir  the destination directory IS the source directory (e.g. a root
 *            item dropped on the volume icon)         FINDER_WIN_ERR_SAMEDIR
 *   cycle    a folder dropped into ITSELF; deeper descendants are caught by
 *            the backend's own '..' walk (fat12_move_dirent step 3) and map to
 *            the same reason                          FINDER_WIN_ERR_CYCLE
 *   exists   the destination already holds the name (a plain move never
 *            clobbers; the Trash path cannot hit this -- it suffixes)
 *                                                     FINDER_WIN_ERR_EXISTS
 *   err      anything else: no binding, no \TRASH, dir full, device
 *                                                     FINDER_WIN_ERR_MOVE
 *   finder_ops_reason() spells the five as "service"|"samedir"|"cycle"|"exists"|"err" for
 *   the kernel's FINDER-MOVE-REFUSED reason=<r> line.
 *
 * TRASH STAGING (design F1.4 / F1.5)
 *   name' = binding.trash_name(name, \TRASH) (fat12_trash_suffix_name: the name
 *   itself when free, else trunc5 + "%03u", lowest free counter), then ONE
 *   binding.move(name -> name', src -> \TRASH) -- the entry is TRANSPLANTED,
 *   never deleted (start_cluster preserved; the mtools differential is the
 *   judge). renamed = (name' != name). Then a kind=5 origin record
 *   {dir_start = src, name83 = name', flags.renamed} joins sh->origins.
 *   Moving an item OUT of \TRASH again drops its origin record.
 *
 * SERIAL (emitted by os/milton/kmain.c from finder_move_result_t):
 *   FINDER-DROP-HILITE name=<n>                    a drop target was LIT
 *                                                  (once per target entered)
 *   FINDER-MOVE name=<n> from=<dir> to=<dir>       a plain move committed
 *   TRASH-RENAME from=<n> to=<n'>                  staging had to suffix
 *   FINDER-TRASH name=<n'> origin=<dir>            staged into \TRASH
 *   FINDER-TRASH-ORIGIN-FULL name=<n'>             staged; origin not kept
 *   FINDER-MOVE-REFUSED reason=<r> name=<n>        the ladder said no
 *   FINDER-WIN-DRAG-REVERT win=<slot> name=<n>     dropped on no target
 *
 * MUTANT KNOBS (Rule 6; -D on finder_ops.c only, never a real build):
 *   FINDER_OPS_MUT_TRASH_NO_STAGE -- the Trash path DELETES (binding.unlink)
 *                                    instead of staging (design F1.4's named
 *                                    TRASH_NO_STAGE).
 *   FINDER_OPS_MUT_NO_CYCLE       -- the folder-into-itself rung is gone.
 *   FINDER_OPS_MUT_NO_ORIGIN      -- staging records no kind=5 origin.
 *   FINDER_OPS_MUT_COUNT_CELL     -- an item dropped on a folder / the volume
 *                                    / the Trash whose window is open lands in
 *                                    cell n (the icon COUNT) instead of the
 *                                    lowest FREE cell, i.e. on top of an icon
 *                                    when the window has a gap (bead
 *                                    initech-tdnl.39, the put-back fix).
 *
 * Ref: docs/design/GUI-remediation-R3-finder-design.md F1.4 (Trash on FAT,
 *        the suffix rule, TRASH-RENAME, TRASH_NO_STAGE), F1.5 (kind=5),
 *        F2.2 ("Icon drag with outline ... on mouseUp hit-test the drop
 *        target: another folder's window content => move-into-folder; the
 *        Trash icon => stage-to-Trash; ... elsewhere => revert"), F3.1 (the
 *        move primitive); docs/plans/GUI-remediation-plan.md R3.4;
 *      os/milton/fat12.h :: fat12_move_dirent / fat12_trash_suffix_name (the
 *        backend the kernel binding wires); bead initech-tdnl.11 NOTES (error
 *        numbers SAME_DIR=-17 / CYCLE=-18 confirmed).
 *      CLAUDE.md Law 1, Law 2, Law 3 (freestanding, dual-compile), Rule 2,
 *        Rule 6, Rule 8, Rule 11, Rule 12.
 */
#ifndef INITECH_OS_FLAIR_FINDER_OPS_H
#define INITECH_OS_FLAIR_FINDER_OPS_H

#include <stdint.h>

#include "finder_windows.h"

typedef enum finder_tgt_kind {
    FINDER_TGT_NONE       = 0,   /* no target: zoom back, nothing changes      */
    FINDER_TGT_REPOSITION = 1,   /* the dragged icon's own window content      */
    FINDER_TGT_WINDOW     = 2,   /* another disk window's content              */
    FINDER_TGT_FOLDER     = 3,   /* a folder icon inside a disk window         */
    FINDER_TGT_VOLUME     = 4,   /* the desktop volume icon (the root)         */
    FINDER_TGT_TRASH      = 5    /* the desktop Trash icon                     */
} finder_tgt_kind_t;

typedef struct finder_tgt {
    uint8_t  kind;      /* finder_tgt_kind_t                                   */
    int8_t   slot;      /* window holding the target; -1 == the desktop        */
    int16_t  idx;       /* target icon on that surface; -1 == no icon          */
    uint16_t dir;       /* destination dir (meaningless for NONE/REPOSITION/
                           TRASH -- the Trash dir comes from the binding)      */
} finder_tgt_t;

/* Resolve the drop target under (h,v) for icon `src_idx` dragged out of window
 * `src_slot`. Reads the shell + WindowMgr (FindWindow); its only write is the
 * geometry re-base of the window under the point (finder_win_view, bead
 * initech-tdnl.34), so the hit is tested against where that window's icons
 * are drawn NOW. */
finder_tgt_t finder_ops_resolve(finder_shell_t *sh, int src_slot,
                                int src_idx, int16_t h, int16_t v);

/* 1 when the target is an ICON that must draw highlighted (FOLDER / VOLUME /
 * TRASH), else 0. */
int finder_ops_tgt_hilites(const finder_tgt_t *t);

/* Move the drop-target highlight from *cur to *next: clear the old icon's
 * hilite, set the new one's, and damage BOTH cells through each surface's one
 * damage entry point (WindowMgr_invalidate_desktop / finder_win_invalidate).
 * *cur becomes *next. Returns 1 when anything changed (the caller repaints),
 * 0 when the highlighted icon is the same. Clearing: pass a NONE target. */
int finder_ops_track_hilite(finder_shell_t *sh, finder_tgt_t *cur,
                            const finder_tgt_t *next);

typedef enum finder_op {
    FINDER_OP_NONE  = 0,
    FINDER_OP_MOVE  = 1,     /* plain cross-directory move                     */
    FINDER_OP_TRASH = 2      /* staged into \TRASH                             */
} finder_op_t;

typedef struct finder_move_result {
    finder_win_status_t status;       /* FINDER_WIN_OK or the ladder's refusal */
    uint8_t  op;                      /* finder_op_t (what was ATTEMPTED)      */
    uint8_t  renamed;                 /* Trash: 1 == a suffix was applied      */
    uint8_t  origin_lost;             /* Trash: 1 == the origin set was full   */
    uint8_t  db_dirty;                /* 1 == the origin set changed           */
    uint16_t from_dir;                /* source directory                      */
    uint16_t to_dir;                  /* destination directory                 */
    int16_t  dst_slot;                /* open window that received the icon    */
    char     name[FINDER_DESK_NAME_MAX];   /* the dragged item's name          */
    char     as[FINDER_DESK_NAME_MAX];     /* its name at the destination      */
} finder_move_result_t;

/* Commit a drop of icon `src_idx` of window `src_slot` onto `t` (WINDOW,
 * FOLDER, VOLUME or TRASH -- REPOSITION/NONE are the caller's). (gx,gy) is the
 * dropped SPRITE origin in global coordinates (the outline's top-left of the
 * sprite), used only when the icon lands in an open window's content.
 *
 * On FINDER_WIN_OK the volume really changed: the icon is gone from the source
 * window (its old cell damaged), present in the destination window when that
 * window is open (whole content damaged), and the origin set updated. On any
 * refusal NOTHING changed -- the models are untouched. `out` is always filled
 * (may not be NULL). */
finder_win_status_t finder_ops_drop(finder_shell_t *sh, int src_slot,
                                    int src_idx, const finder_tgt_t *t,
                                    int16_t gx, int16_t gy,
                                    finder_move_result_t *out);

/* "samedir" | "cycle" | "exists" | "err" for a refusal status. */
const char *finder_ops_reason(finder_win_status_t st);

/* Seed sh->origins from a DESKTOP.DB image (boot), so the whole-file rewrite
 * of the next commit keeps them. Returns the number taken (0 on a corrupt
 * image -- the caller already reported the DB itself). */
uint16_t finder_shell_load_origins(finder_shell_t *sh, const uint8_t *buf,
                                   uint32_t len);

#endif /* INITECH_OS_FLAIR_FINDER_OPS_H */
