/* bin2c.c -- embed a binary file as a C byte array (deterministic).
 *
 * beads: initech-509.5 (the MILTON loader keystone). Used to bake the flat test
 *        program (build/test_program.bin) into the kernel as a .rodata byte
 *        array the loader copies to PROGRAM_IMAGE.
 *
 * Ref:   docs/research/psp-loader-ground-truth.md Sec 5.4 (bake as a C array in
 *        a separate TU -- "the bin2c/xxd approach is simpler and more legible").
 *        CLAUDE.md Law 3 (factory = C), Rule 11 (REPRODUCIBLE: no timestamps,
 *        no host paths in the output; the symbol name is supplied, not derived
 *        from the input path), Rule 12 (ASCII).
 *
 * Usage: bin2c <input.bin> <symbol_name>  > output.h
 *
 * Emits, to stdout:
 *   #include <stdint.h>
 *   const uint8_t <symbol_name>[] = { 0x.., ... };
 *   const uint32_t <symbol_name>_len = <N>u;
 *
 * Deterministic: the bytes are formatted in a fixed layout (12 per line, 0xNN),
 * with no date/time/path. The same input + symbol always yields the same text.
 */

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <input.bin> <symbol_name>\n", argv[0]);
        return 2;
    }

    const char *path = argv[1];
    const char *sym  = argv[2];

    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "bin2c: cannot open %s\n", path);
        return 1;
    }

    /* Header. No timestamp / no input path baked in (Rule 11). */
    printf("/* GENERATED by tools/bin2c -- do NOT edit. Reproducible (Rule 11). */\n");
    printf("#include <stdint.h>\n\n");
    printf("const uint8_t %s[] = {\n", sym);

    unsigned long n = 0;
    int c;
    int col = 0;
    while ((c = fgetc(f)) != EOF) {
        if (col == 0) {
            printf("    ");
        }
        printf("0x%02X,", (unsigned)(c & 0xFF));
        n++;
        col++;
        if (col == 12) {
            printf("\n");
            col = 0;
        } else {
            printf(" ");
        }
    }
    if (col != 0) {
        printf("\n");
    }
    fclose(f);

    printf("};\n\n");
    printf("const uint32_t %s_len = %luu;\n", sym, n);

    return 0;
}
