/*
 * tools/font_art2h.c -- transcribe a hand-authored ASCII-art strike
 * (spec/assets/chicago12.art) into the C header the artifact compiles
 * (spec/assets/chicago12.h). Bead initech-tdnl.33 (slice 1).
 *
 * WHY A TRANSCRIBER: glyph rows are authored as '#'/'.' maps a person can read
 * and review; hand-typing hex rows invites silent bit errors (Rule 12 spirit).
 * The header is a pure function of the .art file, regenerated by
 * `make gen-chicago12` and proven in sync by `make test-chicago-art`.
 *
 * VALIDATION (fail loud, Rule 2 -- a malformed strike never reaches a header):
 *   - glyph blocks are codes FIRST..LAST in order, then exactly one "missing";
 *   - every glyph has exactly CELL_H rows, each exactly `aw` chars of '#'/'.';
 *   - row CELL_H-1 (the leading row) is blank;
 *   - an inked glyph's leftmost ink column == lb (the art agrees with the real
 *     NFNT left bearing written on its glyph line), and the ink image
 *     (rightmost - lb + 1) fits in 16 bits;
 *   - 1 <= aw <= 16, 0 <= lb <= aw (lb == aw only for an inkless glyph:
 *     NFNT 5478 space is lb 4 aw 4).
 *
 * OUTPUT: per glyph, the rows shifted left by lb (image column 0 = the first
 * ink column), MSB = image column 0, as uint16; plus aw[] and lb[]. The
 * renderer places the image at pen + lb and paints the full aw-wide cell.
 *
 * FACTORY CODE (hosted C, Law 3). Deterministic output: no timestamps, no host
 * paths (Rule 11). ASCII-clean (Rule 12).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FIRST  0x20
#define LAST   0x7E
#define COUNT  (LAST - FIRST + 1)
#define CELL_H 16

static unsigned g_rows[COUNT + 1][CELL_H];
static int g_aw[COUNT + 1], g_lb[COUNT + 1];
static char g_art[COUNT + 1][CELL_H][20];
static int g_line;

static void die(const char *msg)
{
    fprintf(stderr, "font_art2h: line %d: %s\n", g_line, msg);
    exit(1);
}

/* Next non-comment line (comments start ';'), newline stripped; NULL at EOF. */
static char *next_line(FILE *f, char *buf, size_t n)
{
    while (fgets(buf, (int)n, f)) {
        size_t l = strlen(buf);
        g_line++;
        while (l && (buf[l - 1] == '\n' || buf[l - 1] == '\r')) buf[--l] = 0;
        if (buf[0] == ';' || l == 0) continue;
        return buf;
    }
    return NULL;
}

int main(int argc, char **argv)
{
    char buf[256];
    FILE *f;
    if (argc != 2) {
        fprintf(stderr, "usage: font_art2h <strike.art>\n");
        return 2;
    }
    f = fopen(argv[1], "r");
    if (!f) { perror(argv[1]); return 2; }

    for (int gi = 0; gi <= COUNT; gi++) {
        char name[32];
        int lb, aw, lo = 99, hi = -1;
        if (!next_line(f, buf, sizeof buf)) die("unexpected EOF (missing glyph block)");
        if (sscanf(buf, "glyph %31s lb %d aw %d", name, &lb, &aw) != 3)
            die("expected 'glyph <code> lb <n> aw <n>'");
        if (gi < COUNT) {
            char want[8];
            snprintf(want, sizeof want, "0x%02X", FIRST + gi);
            if (strcmp(name, want) != 0) die("glyph blocks out of order");
        } else if (strcmp(name, "missing") != 0) {
            die("the last block must be 'missing'");
        }
        if (aw < 1 || aw > 16 || lb < 0 || lb > aw) die("lb/aw out of range");
        for (int r = 0; r < CELL_H; r++) {
            if (!next_line(f, buf, sizeof buf)) die("unexpected EOF inside a glyph");
            if ((int)strlen(buf) != aw) die("row width != aw");
            for (int c = 0; c < aw; c++) {
                if (buf[c] == '#') {
                    if (r == CELL_H - 1) die("ink in the leading row");
                    if (c < lo) lo = c;
                    if (c > hi) hi = c;
                } else if (buf[c] != '.') {
                    die("row chars must be '#' or '.'");
                }
            }
            memcpy(g_art[gi][r], buf, (size_t)aw + 1);
        }
        if (hi >= 0) {
            if (lo != lb) die("leftmost ink column != lb (art disagrees with the NFNT bearing)");
            if (hi - lb + 1 > 16) die("ink image wider than 16 columns");
        }
        for (int r = 0; r < CELL_H; r++) {
            unsigned bits = 0;
            for (int c = lb; c < aw; c++)
                if (g_art[gi][r][c] == '#') bits |= 0x8000u >> (c - lb);
            g_rows[gi][r] = bits;
        }
        g_aw[gi] = aw;
        g_lb[gi] = lb;
    }
    if (next_line(f, buf, sizeof buf)) die("trailing data after the missing glyph");
    fclose(f);

    printf("/*\n"
           " * spec/assets/chicago12.h -- GENERATED by tools/font_art2h.c from\n"
           " * spec/assets/chicago12.art. DO NOT EDIT: edit the .art and run\n"
           " * `make gen-chicago12` (test-chicago-art proves the two are in sync).\n"
           " *\n"
           " * InitechOS \"Chicago 12\" system-font strike (bead initech-tdnl.33).\n"
           " * METRICS (chicago12_aw / chicago12_lb) are the REAL System 7.0.1\n"
           " * Chicago 12 owTable values (NFNT 5478; ../system7-decomp\n"
           " * specs/fonts/chicago.md). GLYPH ART is HAND-AUTHORED (see the\n"
           " * provenance block in chicago12.art); never transcribed from the real\n"
           " * strike bitmap, which may be used only as a diff oracle.\n"
           " *\n"
           " * Rows: chicago12_rows[g][r], MSB = the glyph IMAGE's first column, which\n"
           " * the renderer places at pen + lb; the opaque cell is aw columns wide.\n"
           " * Index g = c - CHICAGO_FIRST for CHICAGO_FIRST <= c <= CHICAGO_LAST;\n"
           " * index CHICAGO_MISSING is the missing-glyph box for every other code.\n"
           " * Linkage: spec/assets/font_linkage.h (one copy per kernel image).\n"
           " */\n"
           "#ifndef INITECH_CHICAGO12_H\n"
           "#define INITECH_CHICAGO12_H\n\n"
           "#include <stdint.h>\n"
           "#include \"font_linkage.h\"\n\n"
           "#define CHICAGO_FIRST   0x%02X\n"
           "#define CHICAGO_LAST    0x%02X\n"
           "#define CHICAGO_COUNT   (CHICAGO_LAST - CHICAGO_FIRST + 1)\n"
           "#define CHICAGO_MISSING CHICAGO_COUNT\n"
           "#define CHICAGO_CELL_H  %d\n"
           "/* NFNT 5478 FontRec: ascent 12, descent 3, leading 1 (chicago.md). */\n"
           "#define CHICAGO_ASCENT  12\n"
           "#define CHICAGO_DESCENT 3\n"
           "#define CHICAGO_LEADING 1\n"
           "/* Art design (chicago12.art): caps + ascenders occupy rows 3..11, so the\n"
           " * first cap row sits CHICAGO_CAP_TOP rows below the cell top. Layout code\n"
           " * places a SAMPLED ink top with cell_top = ink_top - CHICAGO_CAP_TOP. */\n"
           "#define CHICAGO_CAP_TOP 3\n\n",
           FIRST, LAST, CELL_H);

    printf("#if FONT_TABLE_EMIT\n");
    printf("FONT_TABLE unsigned char chicago12_aw[CHICAGO_COUNT + 1] = {");
    for (int gi = 0; gi <= COUNT; gi++)
        printf("%s%d", gi == 0 ? "\n    " : (gi % 16) ? ", " : ",\n    ", g_aw[gi]);
    printf("\n};\n");
    printf("FONT_TABLE unsigned char chicago12_lb[CHICAGO_COUNT + 1] = {");
    for (int gi = 0; gi <= COUNT; gi++)
        printf("%s%d", gi == 0 ? "\n    " : (gi % 16) ? ", " : ",\n    ", g_lb[gi]);
    printf("\n};\n");
    printf("FONT_TABLE uint16_t chicago12_rows[CHICAGO_COUNT + 1][CHICAGO_CELL_H] = {\n");
    for (int gi = 0; gi <= COUNT; gi++) {
        if (gi < COUNT) {
            int c = FIRST + gi;
            printf("/* 0x%02X '%s%c' lb %d aw %d */ {", c,
                   (c == '\\' || c == '\'') ? "\\" : "", (char)c, g_lb[gi], g_aw[gi]);
        } else {
            printf("/* missing lb %d aw %d */ {", g_lb[gi], g_aw[gi]);
        }
        for (int r = 0; r < CELL_H; r++)
            printf("%s0x%04X", r ? "," : "", g_rows[gi][r]);
        printf("},\n");
    }
    printf("};\n#else\n"
           "FONT_TABLE unsigned char chicago12_aw[CHICAGO_COUNT + 1];\n"
           "FONT_TABLE unsigned char chicago12_lb[CHICAGO_COUNT + 1];\n"
           "FONT_TABLE uint16_t chicago12_rows[CHICAGO_COUNT + 1][CHICAGO_CELL_H];\n"
           "#endif\n\n");
    printf("/* Glyph index for byte c: its own slot, or the missing-glyph box. */\n"
           "static inline int chicago12_index(int c)\n"
           "{\n"
           "    if (c < CHICAGO_FIRST || c > CHICAGO_LAST)\n"
           "        return CHICAGO_MISSING;\n"
           "    return c - CHICAGO_FIRST;\n"
           "}\n\n"
           "/* The pen advance of byte c (the owTable aw). */\n"
           "static inline int chicago12_advance(int c)\n"
           "{\n"
           "    return (int)chicago12_aw[chicago12_index(c)];\n"
           "}\n\n"
           "#endif /* INITECH_CHICAGO12_H */\n");
    return 0;
}
